### PR TITLE
Add buttons to the notification for popular tags

### PR DESCRIPTION
**Pull request by geekarist**
This PR adds buttons to notifications, allowing to select a tag in one click for a ping.

The feature is intended to provide some support for smartwatches eg. Android Wear or Samsung Gear, as specified in #42.
I'm currently testing it on my Samsung Gear Sport watch running Tizen 3.0. 

Here is how it's done:
- Create a new broadcast receiver that attributes a tag to a given ping and then sends it to beeminder
- Implement notification actions for a ping by iterating on the most frequently used tags and then creating an action for each of these tags. Each action sends an intent that trigger the broadcast receiver with a given tag and ping ID.

### CODE REVIEW

**Comment by Insti** [comment]
Awesome :star: 

Some questions:

Are the tag buttons also present on phone notifications?

I use Tagtime but I don't want to send all my pings to Beeminder.
There is already support for sending pings containing certain tags to Beeminder. Can this be used?

I often want to tag with the same tags as the previous ping.

Thanks for doing atomic commits :heart:

**Comment by geekarist** [comment]
> Are the tag buttons also present on phone notifications?

Yes they are. In fact there is nothing specific to smartwatch support in this PR. Also that's why it should work on most smartwatch platforms, because they can parse phone notifications and display the buttons on the watch.

> There is already support for sending pings containing certain tags to Beeminder. Can this be used?

Yes, that's how I use it.

> I often want to tag with the same tags as the previous ping.

I think this is a different matter, and there is another issue about that (#48). I could work on it later.

**Comment by Insti** [comment]
(I was waiting for @dreeves to weigh in, but since he seems to not have done so, I'll merge it anyway.)

**Comment by dreeves** [comment]
Thanks so much, both of you! I've been using this version of TagTime for a while now and it works like a charm!

**Pull request merged**
